builds:
- main: ./cmd/biko/main.go
  ldflags: 
    - -s -w
    - -X github.com/KeisukeYamashita/biko/cli.Version={{.Tag}}
  goos:
  - linux
  - darwin
  - windows
brews:
  - tap:
      owner: KeisukeYamashita
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "http://github.com/KeisukeYamashita/biko/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: homebrew-biko
    description: "CLI tool to jump to your browser directly"
    homepage: "https://github.com/KeisukeYamashita/biko"
    test: |
      system "#{bin}/biko --version"
