version: 2.1

executors:
  default:
    working_directory: /go/src/github.com/KeisukeYamashita/biko
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make build
  test:
      executor: default
      steps:
        - checkout
        - run:
            name: Run Test
            command: |
              go test ./...
  release:
    executor: default
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
