[aws]
    [aws.alias]

[azure]
    [azure.alias]

[gcp]
    [gcp.alias]

[datadog]
    [datadog.alias]

[google]
    [google.alias]

[youtube]
    [youtube.alias]

[pagerduty]
    [pagerduty.alias]

[github]
    [github.alias]

[circleci]
    [circleci.alias]

[firebase]
    [firebase.alias]

[jira]
    [jira.alias]
